#option(WITH_HWLOC           "Enable hwloc support" ON)
#option(WITH_TLS             "Enable TLS (Transport Layer Security) support" ON)
#option(WITH_HTTP            "Enable HTTP protocol support (client/server)" ON)
#option(WITH_SODIUM          "Enable libsodium support" ON)
#option(WITH_DEBUG_LOG       "Enable debug log output" OFF)
#option(WITH_CRYPTONOTE      "Enable basic CryptoNote tools (block template and wallet address parsers)" ON)
#option(WITH_CRYPTO_OPS      "Enable miner signatures support (Wownero)" ON)
#option(WITH_CN_LITE         "Enable CryptoNight-Lite algorithms family" ON)
#option(WITH_CN_HEAVY        "Enable CryptoNight-Heavy algorithms family" ON)
#option(WITH_CN_PICO         "Enable CryptoNight-Pico algorithm" ON)
#option(WITH_CN_FEMTO        "Enable CryptoNight-UPX2 algorithm" ON)
#option(WITH_RANDOMX         "Enable RandomX algorithms family" ON)
#option(WITH_ARGON2          "Enable Argon2 algorithms family" ON)
#option(WITH_ASTROBWT        "Enable AstroBWT algorithms family" ON)
#option(WITH_KAWPOW          "Enable KawPow algorithms family" ON)
#option(WITH_ENV_VARS        "Enable environment variables support in config file" ON)
#option(WITH_BENCHMARK       "Enable builtin RandomX benchmark and stress test" OFF)
#option(WITH_SECURE_JIT      "Enable secure access to JIT memory" OFF)
#option(BUILD_STATIC         "Build static binary" OFF)
#option(HWLOC_DEBUG          "Enable hwloc debug helpers and log" OFF)

add_definitions(-D__STDC_FORMAT_MACROS -DUNICODE -D_FILE_OFFSET_BITS=64 -DXMRIG_JSON_SINGLE_LINE_ARRAY)

if (WITH_DEBUG_LOG)
    add_definitions(-DAPP_DEBUG)
endif()

include(CheckIncludeFile)
include(cpu)
include(os)
include(flags)
include(option/tls)
include(option/http)
include(option/hwloc)
include(option/sodium)
include(option/cryptonote)
include(option/algorithms)
include(option/benchmark)
include(option/env)
include(option/syslog)
