if (WITH_ENV_VARS AND CMAKE_CXX_COMPILER_ID MATCHES GNU AND CMAKE_CXX_COMPILER_VERSION VERSION_LESS 4.9)
    set(WITH_ENV_VARS OFF)
endif()

message(STATUS "WITH_ENV_VARS\t= ${WITH_ENV_VARS}")

if (WITH_ENV_VARS)
    add_definitions(-DXMRIG_FEATURE_ENV)
endif()
