find_path(CPUID_INCLUDE_DIR NAMES libcpuid.h)
find_library(CPUID_LIBRARY NAMES cpuid)

mark_as_advanced(CPUID_INCLUDE_DIR CPUID_LIBRARY)

include(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(CPUID DEFAULT_MSG CPUID_LIBRARY CPUID_INCLUDE_DIR)

if(CURL_FOUND)
  set(CPUID_LIBRARIES ${CPUID_LIBRARY})
  set(CPUID_INCLUDE_DIRS ${CPUID_INCLUDE_DIR})
endif()