if (WIN32)
    set(xmlcore_OS_WIN ON)
elseif (APPLE)
    set(xmlcore_OS_APPLE ON)

    if (IOS OR CMAKE_SYSTEM_NAME STREQUAL iOS)
        set(xmlcore_OS_IOS ON)
    else()
        set(xmlcore_OS_MACOS ON)
    endif()
else()
    set(xmlcore_OS_UNIX ON)

    if (ANDROID OR CMAKE_SYSTEM_NAME MATCHES "Android")
        set(xmlcore_OS_ANDROID ON)
    elseif(CMAKE_SYSTEM_NAME MATCHES "Linux")
        set(xmlcore_OS_LINUX ON)
    elseif(CMAKE_SYSTEM_NAME STREQUAL FreeBSD)
        set(xmlcore_OS_FREEBSD ON)
    endif()
endif()


if (xmlcore_OS_WIN)
    add_definitions(/DWIN32)
    add_definitions(/Dxmlcore_OS_WIN)
elseif(xmlcore_OS_APPLE)
    add_definitions(/Dxmlcore_OS_APPLE)

    if (xmlcore_OS_IOS)
        add_definitions(/Dxmlcore_OS_IOS)
    else()
        add_definitions(/Dxmlcore_OS_MACOS)
    endif()

    if (xmlcore_ARM)
        set(WITH_SECURE_JIT ON)
    endif()
elseif(xmlcore_OS_UNIX)
    add_definitions(/Dxmlcore_OS_UNIX)

    if (xmlcore_OS_ANDROID)
        add_definitions(/Dxmlcore_OS_ANDROID)
    elseif (xmlcore_OS_LINUX)
        add_definitions(/Dxmlcore_OS_LINUX)
    elseif (xmlcore_OS_FREEBSD)
        add_definitions(/Dxmlcore_OS_FREEBSD)
    endif()
endif()

if (WITH_SECURE_JIT)
    add_definitions(/Dxmlcore_SECURE_JIT)
endif()
